document:
  name: Tutorial pubblicazione readthedocs su docsitalia
  description: |
    Tutorial pubblicazione readthedocs su docsitalia.    
  tags:
    - readthedocs
    - docsitalia
    - pubblicazione
