document:
  name: Regolamento beni confiscati del comune Palermo
  description: |
    Regolamento beni confiscati del comune Palermo.    
  tags:
    - beni confiscati
    - regolamento
    - comune Palermo
